/* Disallow fuctions
this is very important  
sometimes we not need compiler autogenerated functions
*/
class openFile{
public:
openFile(string filename){cout<<"Open file"<<"\n";}

};

int main(){
openFile f;	//this line autogenerate default constructor but we not need
//because we want to defined our function in this line otherwise some data leeks
} 